// react_app/src/pages/Game/Game.js
import { useEffect, useState } from 'react';

import Apple from '../../assets/img/illustrations/apple.svg';
import Button from '../../elements/Button/Button.js';

import style from './Game.module.css';

function Game() {
  let [count, setCount] = useState(0);
  let [positionImg, setPositionImg] = useState({});

  useEffect(() => {
    changePositionImage()
  }, [])

  const changePositionImage = () => {
    let window_Height = window.innerHeight;
    let window_Width = window.innerWidth;

    let availSpace_V = window_Height - 240;
    let availSpace_H = window_Width - 100;

    let randNum_V = Math.round(Math.random() * availSpace_V) - 30;
    let randNum_H = Math.round(Math.random() * availSpace_H);

    if (randNum_V < 0) { 
      randNum_V = 0;
    } 

    return setPositionImg({top: randNum_V + "px", left: randNum_H + "px"})
  }

  return <>
    <section id={style.gameArea}>
      <div className={`flex-row ${style['action-bar']}`}>
        <Button onClick={() => setCount(0)}>Resetar</Button>
        <p className="text-subtitle">Total de Cliques: <span id="counter">{count}</span> </p>
      </div>
      <img className={style['game-img']} 
                alt="Desenho de uma maçã"
                src={Apple} 
                onClick={() => {
                  setCount(++count)
                  changePositionImage()
                }}
                style={positionImg}/>
    </section>
  </>
}

export default Game;

// angular_app/src/app/game/game.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-game',
  templateUrl: './game.component.html',
  styleUrls: ['./game.component.css']
})
export class GameComponent implements OnInit {
  count: number = 0;
  positionImg: object = this.changePositionImage();
  
  constructor() { }

  changePositionImage() {
    let window_Height: number = window.innerHeight;
    let window_Width: number = window.innerWidth;

    let availSpace_V: number = window_Height - 240;
    let availSpace_H: number = window_Width - 100;

    let randNum_V: number = Math.round(Math.random() * availSpace_V) - 30;
    let randNum_H: number = Math.round(Math.random() * availSpace_H);

    if (randNum_V < 0) { 
      randNum_V = 0;
    } 

    return this.positionImg = {top: randNum_V + "px", left: randNum_H + "px"};
  }

  handleImgClick() {
    ++this.count;
    this.changePositionImage();
  }

  resetCount() {
    this.count = 0;
  }

  ngOnInit(): void {
  }

}

<section id="gameArea">
  <div class="flex-row action-bar">
    <app-button title="Resetar" (click)="resetCount()"></app-button>
    <p class="text-subtitle">Total de Cliques: <span id="counter"> {{ count }} </span></p>
  </div>
  <img class="game-img" alt="Desenho de uma maçã" src="assets/img/apple.svg"
       [ngStyle]="positionImg"
       (click)="handleImgClick()"/>
</section>
