// react_app/src/pages/Game/Game.js
import { useEffect, useState } from 'react';

import Apple from '../../assets/img/illustrations/apple.svg';
import Button from '../../elements/Button/Button.js';

import style from './Game.module.css';

function Game() {
  let [count, setCount] = useState(0);
  let [positionImg, setPositionImg] = useState({});

  useEffect(() => {
    changePositionImage()
  }, [])

  const changePositionImage = () => {
    let window_Height = window.innerHeight;
    let window_Width = window.innerWidth;

    let availSpace_V = window_Height - 240;
    let availSpace_H = window_Width - 100;

    let randNum_V = Math.round(Math.random() * availSpace_V) - 30;
    let randNum_H = Math.round(Math.random() * availSpace_H);

    if (randNum_V < 0) { 
      randNum_V = 0;
    } 

    return setPositionImg({top: randNum_V + "px", left: randNum_H + "px"})
  }

  return <>
    <section id={style.gameArea}>
      <div className={`flex-row ${style['action-bar']}`}>
        <Button onClick={() => setCount(0)}>Resetar</Button>
        <p className="text-subtitle">Total de Cliques: <span id="counter">{count}</span> </p>
      </div>
      <img className={style['game-img']} 
                alt="Desenho de uma maçã"
                src={Apple} 
                onClick={() => {
                  setCount(++count)
                  changePositionImage()
                }}
                style={positionImg}/>
    </section>
  </>
}

export default Game;

// vue_app/src/pages/Game.vue
<template>
  <section id="gameArea">
    <div class="flex-row action-bar">
      <Button @click="count = 0" >Resetar</Button>
      <p class="text-subtitle">Total de Cliques: <span id="counter">{{count}}</span></p>
    </div>
    <img class="game-img" alt="Desenho de uma maçã" src="../assets/img/apple.svg"
         :style="positionImg"
         @click="() => {
          ++count 
          changePositionImage()
         }" />
  </section>
</template>

<script>
import Button from '../elements/Button.vue'

export default {
  name: 'Game',
  components: {
    Button
  },
  data() {
    return { 
      count: 0, 
      positionImg: this.changePositionImage()
    }
  },
  methods: {
    changePositionImage: function() {
      let window_Height = window.innerHeight;
      let window_Width = window.innerWidth;

      let availSpace_V = window_Height - 240;
      let availSpace_H = window_Width - 100;

      let randNum_V = Math.round(Math.random() * availSpace_V) - 30;
      let randNum_H = Math.round(Math.random() * availSpace_H);

      if (randNum_V < 0) { 
        randNum_V = 0;
      } 

      return this.positionImg = {top: randNum_V + "px", left: randNum_H + "px"};
    }
  }
}
</script>

<style scoped>

#gameArea {
  background-color: var(--wine-a005);
  height: calc(100% - 100px);
}

.game-img {
  height: 100px;
  width: 100px;
  position: relative;
  cursor: pointer;
}

.action-bar {
  padding: 15px 20px;
  justify-content: space-between;
  align-items: center;
}

</style>
